### ISSUE TITLE
TicTacToeVerMaim does not work

### ISSUE THREAD

**Issue by michbarsinai** [bThink-BGU/BPjs#33]
Crashes with message:

````
Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "UseSimulatedPlayer" is not defined. (BPJSTicTacToe.js#12)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4142)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4120)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4210)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1952)
	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1891)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1558)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3452)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1244)
	at il.ac.bgu.cs.bp.bpjs.model.BProgram.evaluate(BProgram.java:209)
	... 6 more

````

**Comment by michbarsinai** [comment]
Works now.
