### ISSUE TITLE
Possible serialization bug

### ISSUE THREAD

**Issue by michbarsinai** [bThink-BGU/BPjs#91]
```
java.lang.NullPointerException
at il.ac.bgu.cs.bp.bpjs.model.internal.ContinuationProgramState.collectJsValue(ContinuationProgramState.java:167)
at il.ac.bgu.cs.bp.bpjs.model.internal.ContinuationProgramState.collectScopeValues(ContinuationProgramState.java:83)
at il.ac.bgu.cs.bp.bpjs.model.internal.ContinuationProgramState.<init>(ContinuationProgramState.java:66)
at il.ac.bgu.cs.bp.bpjs.model.BThreadSyncSnapshot.getContinuationProgramState(BThreadSyncSnapshot.java:137)
at il.ac.bgu.cs.bp.bpjs.model.BThreadSyncSnapshot.hashCode(BThreadSyncSnapshot.java:147)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)
at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
at il.ac.bgu.cs.bp.bpjs.model.BProgramSyncSnapshot.executeAllAddedBThreads(BProgramSyncSnapshot.java:294)
at il.ac.bgu.cs.bp.bpjs.model.BProgramSyncSnapshot.start(BProgramSyncSnapshot.java:109)
at il.ac.bgu.cs.bp.bpjs.execution.BProgramRunner.run(BProgramRunner.java:86)
```

I think that the reason for this null is that I used bp.none as interrupt.

**Comment by michbarsinai** [comment]
Could not reproduce. `bp.none`  is used by default as an interrupted set, so might be something else/solved.
